# 웹 터미널 서비스 외부 노출 - NodePort를 통해 클러스터 외부에서 접근 가능
# 접속 주소: http://<K8S_NODE_IP>:31000
apiVersion: v1
kind: Service
metadata:
  name: web-terminal-service
  namespace: claudecode-terminal
  labels:
    app: web-terminal-service
    app.kubernetes.io/part-of: claudecode-web-terminal
spec:
  type: NodePort
  selector:
    app: web-terminal-service
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000
